grails-app/domain/hpmfood/RegistroRefeicaoFunc.groovy
package hpmfood

class RegistroRefeicaoFunc {

    Date entradaAlmoco
    Date saidaAlmoco

    static belongsTo = [funcionario: Pessoa]

    static constraints = {
        funcionario nullable: false
        entradaAlmoco nullable: false
        saidaAlmoco nullable: true
    }
}

grails-app/controllers/hpmfood/RegistroRefeicaoFuncController.groovy
package hpmfood

import grails.converters.JSON

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RegistroRefeicaoFuncController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    RegistroRefeicaoFuncService registroRefeicaoFuncService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond RegistroRefeicaoFunc.list(params), model:[registroRefeicaoFuncCount: RegistroRefeicaoFunc.count()]
    }

    def show(RegistroRefeicaoFunc registroRefeicaoFunc) {
        respond registroRefeicaoFunc
    }

    def create() {
        respond new RegistroRefeicaoFunc(params)
    }

    def retornaPessoaDados(){


        def dadosFuncionario = Pessoa.findByCpf(params.cpfDados)
        render(dadosFuncionario as JSON)
    }

    @Transactional
    def save(def params) {

        Pessoa pessoa = Pessoa.findByCpf(params.cpfDados)

        RegistroRefeicaoFunc registro = new RegistroRefeicaoFunc()
        registro.funcionario = pessoa
        registro.entradaAlmoco = new Date()
        registro.save(flush: true, failOnError: true)

        flash.message = "Olá ${pessoa.nome} seu Registro de refeição foi efetuado"
        redirect(action: 'create')

    }

    def edit(RegistroRefeicaoFunc registroRefeicaoFunc) {
        respond registroRefeicaoFunc
    }

    @Transactional
    def update(RegistroRefeicaoFunc registroRefeicaoFunc) {
        if (registroRefeicaoFunc == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (registroRefeicaoFunc.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond registroRefeicaoFunc.errors, view:'edit'
            return
        }

        registroRefeicaoFunc.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'registroRefeicaoFunc.label', default: 'RegistroRefeicaoFunc'), registroRefeicaoFunc.id])
                redirect registroRefeicaoFunc
            }
            '*'{ respond registroRefeicaoFunc, [status: OK] }
        }
    }

    @Transactional
    def delete(RegistroRefeicaoFunc registroRefeicaoFunc) {

        if (registroRefeicaoFunc == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        registroRefeicaoFunc.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'registroRefeicaoFunc.label', default: 'RegistroRefeicaoFunc'), registroRefeicaoFunc.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'registroRefeicaoFunc.label', default: 'RegistroRefeicaoFunc'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/registroRefeicaoFunc/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'registroRefeicaoFunc.label', default: 'RegistroRefeicaoFunc')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body onload="moveRelogio()">
<main class="mt25">
    <g:if test="${flash.message}">
        <section class="container">
            <h6 class="center">${flash.message}</h6>
        </section>
    </g:if>

    <section class="container">
        <div class="card">
            <div class="card-content">
                <div class="card-title center" id="relogio_id">

                </div>
                <g:form method="post" action="save" controller="registroRefeicaoFunc" class="formRegistroRef">
                    <div class="row">
                        <div class="input-field col s6">
                            <input autofocus id="cpfFuncionario" type="text" class="validate" name="cpfDados">
                            <label for="cpfFuncionario">CPF</label>
                        </div>

                        <div class="input-field col s6">
                            <input id="nome_id" type="text">
                            <span class="helper-text" data-error="wrong" data-success="right">Nome</span>
                        </div>

                        <div class="input-field col s6">
                            <input id="telefone_id" type="text">
                            <span class="helper-text" data-error="wrong" data-success="right">Telefone</span>
                        </div>

                        <div class="input-field col s6">
                            <div class="right-align">
                                <button type="button" id="btnSubmit" class="btn green white-text">Registrar Refeição</button>
                            </div>
                        </div>

                        %{--<input id="pessoa_id" type="text" class="validate" name="pessoaId">--}%
                    </div>
                </g:form>
            </div>
        </div>
    </section>
</main>
<input hidden id="listDadosPessoa"
       value="${createLink(controller: 'registroRefeicaoFunc', action: 'retornaPessoaDados')}"/>
</body>
</html>

grails-app/views/registroRefeicaoFunc/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'registroRefeicaoFunc.label', default: 'RegistroRefeicaoFunc')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-registroRefeicaoFunc" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-registroRefeicaoFunc" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.registroRefeicaoFunc}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.registroRefeicaoFunc}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.registroRefeicaoFunc}" method="PUT">
                <g:hiddenField name="version" value="${this.registroRefeicaoFunc?.version}" />
                <fieldset class="form">
                    <f:all bean="registroRefeicaoFunc"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/registroRefeicaoFunc/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'registroRefeicaoFunc.label', default: 'RegistroRefeicaoFunc')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-registroRefeicaoFunc" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-registroRefeicaoFunc" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${registroRefeicaoFuncList}" />

            <div class="pagination">
                <g:paginate total="${registroRefeicaoFuncCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/registroRefeicaoFunc/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'registroRefeicaoFunc.label', default: 'RegistroRefeicaoFunc')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-registroRefeicaoFunc" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-registroRefeicaoFunc" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="registroRefeicaoFunc" />
            <g:form resource="${this.registroRefeicaoFunc}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.registroRefeicaoFunc}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>